kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.image.repository }}-nginx-config
data:
  nginx.conf: |
    events {

    }

    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/stewartmarsh.test/public_html;
        server_name _;

        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;

        index index.html index.html index.php;
        charset utf-8;

        location / {
          include /etc/nginx/mime.types;
          try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt { access_log off; log_not_found off; }

        error_page 404 /index.php;

        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_index index.php;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }
