apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.image.repository }}-deployment"
  labels:
    app: "{{ .Values.image.repository }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.image.repository }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.image.repository }}"
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: {{ .Values.image.repository }}-nginx-config
        - name: local-mount
          hostPath:
            path: {{ .Values.projectPath }}
      containers:
        - name: app
          image: "stewartmarsh:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          volumeMounts:
            - name: local-mount
              mountPath: /var/www/stewartmarsh.test

        - name: nginx
          image: nginx:1.19-alpine
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: local-mount
              mountPath: /var/www/stewartmarsh.test


